export const siteConfig = {
  name: "Jeffrey Tottimeh",
  title: "Jeffrey Tottimeh - CEO & Founder | Full Stack Developer",
  description: "CEO & Founder of Hatchers Dev Studio and ARC Robotics Challenge. Full-stack developer specializing in web, mobile, and IoT solutions.",
  url: "https://roboticsandcoding.me",
  author: {
    name: "Jeffrey Tottimeh",
    role: "CEO & Founder",
    bio: "Innovative technology leader, entrepreneur, and full-stack developer passionate about building solutions that transform businesses and empower communities.",
    email: "contact@hatchersdev.studio",
    location: "Ghana 🇬🇭",
  },
  social: {
    twitter: "https://twitter.com/tottimehjeffrey",
    linkedin: "https://gh.linkedin.com/in/jeffrey-tottimeh-135693319",
    youtube: "https://www.youtube.com/channel/UCZIBw2LZdsXzqNeds22z_Fg",
    instagram: "https://www.instagram.com/junior_billyhills",
    tiktok: "https://www.tiktok.com/@lil_jay",
    github: "https://github.com/TA-wiah",
  },
  companies: {
    hatchers: {
      name: "Hatchers Dev Studio",
      tagline: "Building cutting-edge software solutions",
      description: "A full-service software development studio specializing in web applications, mobile apps, IoT solutions, and UI/UX design.",
      services: [
        {
          name: "Web Development",
          description: "Modern, responsive websites and web applications built with the latest technologies.",
          icon: "FaCode",
        },
        {
          name: "Mobile Development",
          description: "Native and cross-platform mobile applications for iOS and Android.",
          icon: "FaMobile",
        },
        {
          name: "IoT Solutions",
          description: "Smart automation systems and embedded solutions for homes and industries.",
          icon: "FaMicrochip",
        },
        {
          name: "UI/UX Design",
          description: "Beautiful, user-centered designs that enhance user experience.",
          icon: "FaPaintBrush",
        },
      ],
    },
    arc: {
      name: "ARC Robotics Challenge",
      tagline: "Inspiring the next generation of engineers",
      description: "A robotics competition platform empowering students to learn, innovate, and compete in the field of robotics and automation.",
      mission: "To inspire and educate the next generation of engineers through hands-on robotics challenges and STEM education.",
      impact: [
        "500+ students participated",
        "50+ schools engaged",
        "100+ robots built",
        "10+ annual competitions",
      ],
    },
  },
  techStack: {
    languages: ["Python", "TypeScript", "JavaScript", "PHP", "Kotlin", "Dart", "C++", "C"],
    frontend: ["React", "Next.js", "HTML5", "CSS3", "Tailwind CSS", "Bootstrap", "Figma"],
    backend: ["Node.js", "Django", "Flask", ".NET", "Express"],
    databases: ["MongoDB", "MySQL", "PostgreSQL", "Redis", "Firebase"],
    mobile: ["Flutter", "React Native", "Kotlin", "Android Studio"],
    robotics: ["Arduino", "Raspberry Pi", "Linux", "Qt"],
    tools: ["Git", "GitHub", "Docker", "VS Code", "Electron", "Blender"],
  },
  achievements: [
    {
      year: "2024",
      title: "Founded Hatchers Dev Studio",
      description: "Launched a full-service software development studio",
    },
    {
      year: "2023",
      title: "ARC Robotics Challenge",
      description: "Organized first annual robotics competition",
    },
    {
      year: "2023",
      title: "15+ Production Apps",
      description: "Built and deployed applications for clients worldwide",
    },
    {
      year: "2022-2024",
      title: "Mentored 50+ Developers",
      description: "Guided aspiring developers in full-stack development",
    },
  ],
  projects: [
    {
      id: 1,
      title: "Hatchers Dev Studio Website",
      description: "Official company portfolio showcasing services and client work",
      category: "Web Development",
      technologies: ["Next.js", "TypeScript", "Tailwind CSS"],
      status: "In Development",
      image: "/images/projects/hatchers-website.jpg",
    },
    {
      id: 2,
      title: "ARC Robotics Platform",
      description: "Competition management and learning platform for robotics students",
      category: "Web Development",
      technologies: ["React", "Node.js", "MongoDB"],
      status: "Coming Soon",
      image: "/images/projects/arc-platform.jpg",
    },
    {
      id: 3,
      title: "IoT Automation Suite",
      description: "Smart home and industrial automation control system",
      category: "IoT",
      technologies: ["Python", "Arduino", "MQTT", "React"],
      status: "In Progress",
      image: "/images/projects/iot-suite.jpg",
    },
    {
      id: 4,
      title: "Mobile Banking App",
      description: "Secure fintech solution for microfinance operations",
      category: "Mobile Development",
      technologies: ["Flutter", "Firebase", "Node.js"],
      status: "Private",
      image: "/images/projects/banking-app.jpg",
    },
  ],
}
